### ISSUE TITLE
Nested processing

### ISSUE THREAD

**Issue by TeoTN** [EfogDev/react-process-string#1]
There is an issue with nested processing: the rules are applied in the order they were provided, whereas in order to recursively handle nested patterns it should apply rules from the broadest to the narrowest.
Example: 
```
import processString from 'react-process-string';


class Processor {
    constructor() {
        this.config = [{
            regex: /(\*\*)([^*]+)(\*\*)/gim,  // **bold text**
            fn: (key, result) => <strong key={key}>{this.format(result[2])}</strong>
        }, {
            regex: /(__)([^_]+)(__)/gim,  // **italic text**
            fn: (key, result) => <em key={key}>{this.format(result[2])}</em>
        }];
    }

    format(content) {
        return processString(this.config)(content);
    }
}
export default Processor;

```

Please compare results of `processor.format("__**case 1**__")` and `processor.format("**__case 2__**")`. Could you please review the issue and suggest how it can be solved?

**Comment by efogdev** [comment]
Thanks for reporting an issue! Actually, it isn't a bug, it is pretty much expected behavior.
I don't think the library would be helpful in your specific case.

In the library we manipulate with react elements, not just strings. I guess the problem could only be solved by processing pure HTML and then setting `__dangerouslySetHTML`.
